version: '3.8'

services:
  bot:
    image: ghcr.io/az2oo1/wa-bot:latest
    ports:
      - "3000:3000"
    environment:
      - WA_DATA_DIR=/data
      - WA_AUTH_PATH=/data/.wwebjs_auth
      - WA_BROWSER_PROFILE_DIR=/data/chromium-profile
    volumes:
      - /DATA/AppData/wa-bot:/data
    restart: unless-stopped