version: '3.8'

services:
  bot:
    image: ghcr.io/az2oo1/wa-bot:latest
    ports:
      - "3000:3000"
    volumes:
      - /DATA/AppData/wa-bot:/app
      - /app/.wwebjs_cache
      - /app/.puppeteer_cache
      - /root/.local/share/chromium
      - /root/.config/chromium
    environment:
      - PUPPETEER_DISABLE_HEADFUL_MODE=true
    restart: unless-stopped